[package]
name = "todo_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
sea-orm = {version = "1.1.0", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"]}